<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'18rRttKqzsU=');
$cfg_Cs[2]=array(0,1,1,'udu148jxxsA=');
$cfg_Cs[3]=array(0,1,1,'1sfE3NOyvP4=');
$cfg_Cs[4]=array(0,1,1,'18qxvravzKw=');
$cfg_Cs[5]=array(0,1,1,'16i80teowLg=');
$cfg_Cs[10]=array(0,1,1,'sLjA/bfWzvY=');
$cfg_Cs[7]=array(0,1,1,'TzJPu+62rw==');
$cfg_Cs[8]=array(0,1,1,'yv2+3cf9tq8=');
$cfg_Cs[11]=array(0,2,1,'zbzLtczsz8I=');
?>