<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/150410/1-150410202021.png ",93,243);
$z[1][4]['ddimg']="/uploads/allimg/150410/1-150410202021.png";
$z[1][4]['text']="213";
$z[1][4]['width']="500";
$z[1][4]['height']="375";
$z[2]=Array("img"," /uploads/allimg/150410/1-150410202025.png ",245,394);
$z[2][4]['ddimg']="/uploads/allimg/150410/1-150410202025.png";
$z[2][4]['text']="23";
$z[2][4]['width']="500";
$z[2][4]['height']="375";

?>