<?php
$z[0]=Array("global","",76,101);
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",137,152);
$z[2]=Array("fulltitle","",161,179);
$z[3]=Array("title","",181,195);
$z[4]=Array("arcurl","",274,289);
$z[5]=Array("fulltitle","",298,316);
$z[6]=Array("litpic","",328,343);
$z[7]=Array("fulltitle","",374,392);
$z[8]=Array("arcurl","",455,470);
$z[9]=Array("fulltitle","",479,497);
$z[10]=Array("info","",499,512);

?>