<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/141112/8-141112102614.jpg ",93,241);
$z[1][4]['ddimg']="/uploads/allimg/141112/8-141112102614.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="950";
$z[1][4]['height']="1425";
$z[2]=Array("img"," /uploads/allimg/141112/8-141112102615.jpg ",243,391);
$z[2][4]['ddimg']="/uploads/allimg/141112/8-141112102615.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="950";
$z[2][4]['height']="1373";

?>