<li class="item clearfix">
          <div class="tit"> <em class="n fl">0[field:global.autoindex/]</em> <a class="fs_14" href="[field:arcurl/]" title="[field:fulltitle/]">[field:title/]</a> </div>
          <div class="sub g_picarc"> <a class="img" href="[field:arcurl/]" title="[field:fulltitle/]"><img src="[field:litpic/]" height="90" width="120" alt="[field:title /]" /></a>
            <p class="infos"><a class="fc_666 ful_n" href="arcurl" title="[field:fulltitle/]">[field:info/]</a></p>
          </div>
        </li>