<li class="item mb clearfix">
				<a class="img" href="[field:arcurl/]" title="[field:fulltitle/]"><img class="lazy" src="[field:litpic/]" height="90" width="120" alt="[field:fulltitle/]" /></a>
				<div class="summary">
					<div class="t hidtit fa_yhei"><a class="fs_14" href="[field:arcurl/]" title="[field:fulltitle/]">[field:title/]</a></div>
					<p class="infos hidtit fc_999">[field:info/]</p>
				</div>
			</li>