<?php
$z[0]=Array("channel","\r\n    - <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n   ",93,204);
$z[0][4]['type']="top";
$z[0][4]['row']="10";
$z[1]=Array("global","",244,278);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",318,347);
$z[2][4]['name']="cfg_wap";
$z[3]=Array("global","",402,435);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",436,467);
$z[4][4]['name']="cfg_beian";

?>