<?php
$z[0]=Array("global","",1207,1233);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",1275,1301);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",1358,1381);
$z[2][4]['name']="cfg_mail";
$z[3]=Array("field","(@me==\"\")? @me=\" class='cur'\":@me=\"\";",2164,2251);
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channel"," <a href=\"[field:typelink/]\" title=\"[field:typename function='substr(@me,0,12)'/]\" >[field:typename function='substr(@me,0,12)'/]</a> ",2265,2511);
$z[4][4]['row']="10";
$z[4][4]['type']="top";
$z[4][4]['currentstyle']="<a href='~typelink~' class='cur'>~typename~</a>";

?>