<?php
$z[0]=Array("field","",243,265);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",266,292);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",333,355);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",395,446);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",647,669);
$z[4][4]['name']="cfg_wap";
$z[5]=Array("include","",1202,1237);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",1340,1369);
$z[6][4]['name']="position";
$z[7]=Array("list","\r\n				<a class=\"item fl\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"><img class=\"lazy\" src=\"[field:litpic/]\"  height=\"188\" width=\"158\" alt=\"[field:fulltitle/]\" /><span class=\"t hidtit_2\" title=\"[field:fulltitle/]\">[field:title/]</span></a>\r\n			",1442,1743);
$z[7][4]['pagesize']="20";
$z[7][4]['titlelen']="30";
$z[8]=Array("pagelist","",1817,1873);
$z[8][4]['listitem']="pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1896,1932);
$z[9][4]['filename']="right.htm";
$z[10]=Array("include","",1944,1979);
$z[10][4]['filename']="foot.htm";

?>