<?php
$z[0]=Array("myad","",70,100);
$z[0][4]['name']="public_ad1";
$z[1]=Array("type","[field:typename /]",193,246);
$z[1][4]['typeid']="1";
$z[2]=Array("arclist","\r\n    <h4 class=\"mb fs_18 fa_yhei ftc\"><a class=\"fc_36a\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a></h4>\r\n    ",269,476);
$z[2][4]['row']="1";
$z[2][4]['flag']="c";
$z[2][4]['titlelen']="40";
$z[2][4]['typeid']="1";
$z[3]=Array("arclist","\r\n      <li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a></li>\r\n      ",524,695);
$z[3][4]['row']="6";
$z[3][4]['titlelen']="54";
$z[3][4]['typeid']="1";
$z[4]=Array("myad","",745,775);
$z[4][4]['name']="public_ad2";
$z[5]=Array("type","[field:typename /]",868,921);
$z[5][4]['typeid']="2";
$z[6]=Array("arclist","\r\n      <li class=\"item mb clearfix\"> <a class=\"img\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"><img class=\"lazy\" src=\"[field:litpic/]\" height=\"75\" width=\"100\" alt=\"[field:title /]\" /></a>\r\n        <div class=\"summary\">\r\n          <div class=\"t hidtit fa_yhei\"><a class=\"fs_14\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a></div>\r\n          <p class=\"infos fc_999\">[field:info/]</p>\r\n        </div>\r\n      </li>\r\n      ",973,1506);
$z[6][4]['row']="3";
$z[6][4]['flag']="p";
$z[6][4]['titlelen']="60";
$z[6][4]['infolen']="50";
$z[6][4]['typeid']="2";
$z[7]=Array("arclist","\r\n        <li class=\"item clearfix\">\r\n          <div class=\"tit\"> <em class=\"n fl\">0[field:global.autoindex/]</em> <a class=\"fs_14\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]</a> </div>\r\n          <div class=\"sub g_picarc\"> <a class=\"img\" href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\"><img src=\"[field:litpic/]\" height=\"90\" width=\"120\" alt=\"[field:title /]\" /></a>\r\n            <p class=\"infos\"><a class=\"fc_666 ful_n\" href=\"arcurl\" title=\"[field:fulltitle/]\">[field:info/]</a></p>\r\n          </div>\r\n        </li>\r\n        ",1709,2346);
$z[7][4]['row']="10";
$z[7][4]['flag']="p";
$z[7][4]['titlelen']="60";
$z[7][4]['infolen']="70";
$z[7][4]['typeid']="all";
$z[8]=Array("myad","",2410,2440);
$z[8][4]['name']="public_ad3";

?>